"""baseline: all existing tables (v1 + v2 + v3)

Revision ID: 86fbcc9926b2
Revises: 
Create Date: 2026-05-18 10:16:34.486368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86fbcc9926b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_details', sa.Text(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)

    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('used', sa.Float(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_id'), ['id'], unique=False)

    op.create_table('material_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('material_type', sa.Enum('COIL', 'BILLET', 'SLAB', 'SHEET', 'BAR', 'PLATE', 'PIPE', 'ANGLE', 'CHANNEL', 'BEAM', 'SCRAP', 'OTHER', name='materialtype'), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('thickness_mm', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('width_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('length_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('diameter_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('default_unit', sa.Enum('KG', 'TON', 'MT', 'PIECE', 'METER', 'FEET', name='weightunit'), nullable=True),
    sa.Column('reorder_level', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('min_order_qty', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('sub_category', sa.String(length=50), nullable=True),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_master_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_material_master_id'), ['id'], unique=False)
        batch_op.create_index('ix_material_type_grade', ['material_type', 'grade'], unique=False)

    op.create_table('number_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_name', sa.String(length=50), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=True),
    sa.Column('current_number', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('padding', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_name')
    )
    with op.batch_alter_table('number_sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_number_sequences_id'), ['id'], unique=False)

    op.create_table('role_notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('in_app', sa.Boolean(), nullable=True),
    sa.Column('email', sa.Boolean(), nullable=True),
    sa.Column('push', sa.Boolean(), nullable=True),
    sa.Column('instr_from_boss', sa.Boolean(), nullable=True),
    sa.Column('stage_changes', sa.Boolean(), nullable=True),
    sa.Column('query_raised', sa.Boolean(), nullable=True),
    sa.Column('query_response', sa.Boolean(), nullable=True),
    sa.Column('low_inventory', sa.Boolean(), nullable=True),
    sa.Column('dispatch_completed', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    with op.batch_alter_table('role_notification_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_notification_settings_id'), ['id'], unique=False)

    op.create_table('storage_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location_type', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('capacity_tons', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('current_occupancy_tons', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('is_covered', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['storage_locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('storage_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storage_locations_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_id'), ['id'], unique=False)

    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index('ix_audit_user_date', ['user_id', 'created_at'], unique=False)

    op.create_table('dispatch_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sales_order_ref', sa.String(length=50), nullable=True),
    sa.Column('vehicle_number', sa.String(length=20), nullable=True),
    sa.Column('transporter', sa.String(length=100), nullable=True),
    sa.Column('driver_name', sa.String(length=100), nullable=True),
    sa.Column('driver_contact', sa.String(length=20), nullable=True),
    sa.Column('gross_weight_kg', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('tare_weight_kg', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('net_weight_kg', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'CANCELLED', name='documentstatus'), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatch_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_notes_dispatch_number'), ['dispatch_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_dispatch_notes_id'), ['id'], unique=False)

    op.create_table('excel_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('excel_uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_excel_uploads_id'), ['id'], unique=False)

    op.create_table('goods_receipt_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grn_number', sa.String(length=50), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('vendor_invoice_number', sa.String(length=50), nullable=True),
    sa.Column('vendor_invoice_date', sa.DateTime(), nullable=True),
    sa.Column('vehicle_number', sa.String(length=20), nullable=True),
    sa.Column('driver_name', sa.String(length=100), nullable=True),
    sa.Column('driver_contact', sa.String(length=20), nullable=True),
    sa.Column('gross_weight_kg', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('tare_weight_kg', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('net_weight_kg', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('weighbridge_slip_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'CANCELLED', name='documentstatus'), nullable=True),
    sa.Column('gate_entry_time', sa.DateTime(), nullable=True),
    sa.Column('weighment_time', sa.DateTime(), nullable=True),
    sa.Column('received_time', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('received_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goods_receipt_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_receipt_notes_grn_number'), ['grn_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_goods_receipt_notes_id'), ['id'], unique=False)

    op.create_table('instructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instructions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instructions_id'), ['id'], unique=False)

    op.create_table('material_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('excel_name', sa.String(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_mappings_excel_name'), ['excel_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_material_mappings_id'), ['id'], unique=False)

    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('in_app', sa.Boolean(), nullable=True),
    sa.Column('email', sa.Boolean(), nullable=True),
    sa.Column('push', sa.Boolean(), nullable=True),
    sa.Column('instr_from_boss', sa.Boolean(), nullable=True),
    sa.Column('stage_changes', sa.Boolean(), nullable=True),
    sa.Column('query_raised', sa.Boolean(), nullable=True),
    sa.Column('query_response', sa.Boolean(), nullable=True),
    sa.Column('low_inventory', sa.Boolean(), nullable=True),
    sa.Column('dispatch_completed', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_settings_id'), ['id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)

    op.create_table('production_items_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('length_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('width_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('thickness_mm', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ordered_qty', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('produced_qty', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('estimated_weight_kg', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('actual_weight_kg', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_items_v2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_items_v2_id'), ['id'], unique=False)

    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_config_id'), ['id'], unique=False)

    op.create_table('v3_drawings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drawing_number', sa.String(length=100), nullable=False),
    sa.Column('revision', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('project_ref', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'DETAILED', 'CHECKED', 'RELEASED', 'IN_PROGRESS', 'COMPLETE', 'ON_HOLD', 'CANCELLED', name='drawingstatus'), nullable=False),
    sa.Column('total_weight_kg', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('completed_weight_kg', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('released_date', sa.DateTime(), nullable=True),
    sa.Column('released_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['released_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drawing_number', 'revision', 'customer_id', name='uq_drawing_number_rev_customer')
    )
    with op.batch_alter_table('v3_drawings', schema=None) as batch_op:
        batch_op.create_index('ix_drawing_customer', ['customer_id'], unique=False)
        batch_op.create_index('ix_drawing_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_v3_drawings_drawing_number'), ['drawing_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_v3_drawings_id'), ['id'], unique=False)

    op.create_table('v3_stage_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('stage_name', sa.String(length=50), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('requires_qa_hold', sa.Boolean(), nullable=True),
    sa.Column('auto_deduct_material', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'stage_name', name='uq_stage_config_customer_stage')
    )
    with op.batch_alter_table('v3_stage_configs', schema=None) as batch_op:
        batch_op.create_index('ix_stage_config_customer', ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_v3_stage_configs_id'), ['id'], unique=False)

    op.create_table('grn_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('heat_number', sa.String(length=50), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('ordered_qty', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('received_qty', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('accepted_qty', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('rejected_qty', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('unit', sa.Enum('KG', 'TON', 'MT', 'PIECE', 'METER', 'FEET', name='weightunit'), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('qa_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'ON_HOLD', 'CONDITIONAL', name='qastatus'), nullable=True),
    sa.Column('qa_remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['grn_id'], ['goods_receipt_notes.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grn_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grn_line_items_id'), ['id'], unique=False)

    op.create_table('production_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('length_mm', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('weight_per_unit', sa.Float(), nullable=True),
    sa.Column('material_requirements', sa.Text(), nullable=True),
    sa.Column('checklist', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('current_stage', sa.String(), nullable=False),
    sa.Column('stage_updated_at', sa.DateTime(), nullable=True),
    sa.Column('stage_updated_by', sa.Integer(), nullable=True),
    sa.Column('fabrication_deducted', sa.Boolean(), nullable=True),
    sa.Column('material_deducted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('parent_item_id', sa.Integer(), nullable=True),
    sa.Column('excel_upload_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['excel_upload_id'], ['excel_uploads.id'], ),
    sa.ForeignKeyConstraint(['parent_item_id'], ['production_items.id'], ),
    sa.ForeignKeyConstraint(['stage_updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_items_id'), ['id'], unique=False)

    op.create_table('stage_tracking_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_item_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['production_item_id'], ['production_items_v2.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_item_id', 'stage', name='uq_item_stage_v2')
    )
    with op.batch_alter_table('stage_tracking_v2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_tracking_v2_id'), ['id'], unique=False)
        batch_op.create_index('ix_stage_v2_item_status', ['production_item_id', 'status'], unique=False)

    op.create_table('stock_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=50), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('heat_number', sa.String(length=50), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('coil_number', sa.String(length=50), nullable=True),
    sa.Column('gross_weight_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('tare_weight_kg', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('net_weight_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('current_weight_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('initial_quantity', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('current_quantity', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('unit', sa.Enum('KG', 'TON', 'MT', 'PIECE', 'METER', 'FEET', name='weightunit'), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('grn_id', sa.Integer(), nullable=True),
    sa.Column('purchase_rate', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('qa_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'ON_HOLD', 'CONDITIONAL', name='qastatus'), nullable=True),
    sa.Column('qa_remarks', sa.Text(), nullable=True),
    sa.Column('test_certificate_ref', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('received_date', sa.DateTime(), nullable=False),
    sa.Column('manufacture_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('block_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('current_weight_kg <= net_weight_kg', name='ck_current_not_exceed_net'),
    sa.CheckConstraint('current_weight_kg >= 0', name='ck_current_weight_positive'),
    sa.CheckConstraint('net_weight_kg <= gross_weight_kg', name='ck_net_not_exceed_gross'),
    sa.ForeignKeyConstraint(['grn_id'], ['goods_receipt_notes.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['storage_locations.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material_master.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_lots', schema=None) as batch_op:
        batch_op.create_index('ix_stock_lot_heat', ['heat_number'], unique=False)
        batch_op.create_index('ix_stock_lot_location', ['location_id'], unique=False)
        batch_op.create_index('ix_stock_lot_material_qa', ['material_id', 'qa_status'], unique=False)
        batch_op.create_index('ix_stock_lot_vendor_date', ['vendor_id', 'received_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_lots_heat_number'), ['heat_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_lots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_lots_lot_number'), ['lot_number'], unique=True)

    op.create_table('v3_assemblies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drawing_id', sa.Integer(), nullable=False),
    sa.Column('mark_number', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('quantity_required', sa.Integer(), nullable=False),
    sa.Column('quantity_complete', sa.Integer(), nullable=True),
    sa.Column('total_weight_kg', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drawing_id'], ['v3_drawings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drawing_id', 'mark_number', name='uq_assembly_drawing_mark')
    )
    with op.batch_alter_table('v3_assemblies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_v3_assemblies_id'), ['id'], unique=False)

    op.create_table('v3_drawing_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drawing_id', sa.Integer(), nullable=False),
    sa.Column('from_revision', sa.String(length=10), nullable=False),
    sa.Column('to_revision', sa.String(length=10), nullable=False),
    sa.Column('revision_date', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('received_from', sa.String(length=200), nullable=True),
    sa.Column('bom_diff', sa.JSON(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['drawing_id'], ['v3_drawings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('v3_drawing_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_v3_drawing_revisions_id'), ['id'], unique=False)

    op.create_table('dispatch_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('stock_lot_id', sa.Integer(), nullable=False),
    sa.Column('dispatched_weight_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('dispatched_qty', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('rate', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatch_notes.id'], ),
    sa.ForeignKeyConstraint(['stock_lot_id'], ['stock_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatch_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_line_items_id'), ['id'], unique=False)

    op.create_table('material_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('production_item_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('by', sa.String(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['production_item_id'], ['production_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_usage_id'), ['id'], unique=False)

    op.create_table('queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('production_item_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['production_item_id'], ['production_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queries_id'), ['id'], unique=False)

    op.create_table('reusable_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(), nullable=False),
    sa.Column('length_mm', sa.Float(), nullable=True),
    sa.Column('width_mm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('dimensions', sa.String(), nullable=False),
    sa.Column('source_item_id', sa.Integer(), nullable=True),
    sa.Column('source_customer_id', sa.Integer(), nullable=True),
    sa.Column('quality_grade', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('used_in_item_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['source_item_id'], ['production_items.id'], ),
    sa.ForeignKeyConstraint(['used_in_item_id'], ['production_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reusable_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reusable_stock_id'), ['id'], unique=False)

    op.create_table('scrap_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('length_mm', sa.Float(), nullable=True),
    sa.Column('width_mm', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('source_item_id', sa.Integer(), nullable=True),
    sa.Column('source_customer_id', sa.Integer(), nullable=True),
    sa.Column('dimensions', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('scrap_value', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['source_item_id'], ['production_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrap_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrap_records_id'), ['id'], unique=False)

    op.create_table('stage_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_item_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['production_item_id'], ['production_items.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stage_tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_tracking_id'), ['id'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_number', sa.String(length=50), nullable=False),
    sa.Column('stock_lot_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('INWARD_PURCHASE', 'INWARD_RETURN', 'INWARD_TRANSFER', 'OUTWARD_SALE', 'OUTWARD_TRANSFER', 'OUTWARD_SCRAP', 'CONSUMPTION', 'ADJUSTMENT_PLUS', 'ADJUSTMENT_MINUS', 'REWEIGH', 'SPLIT', 'MERGE', name='movementtype'), nullable=False),
    sa.Column('weight_change_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('weight_before_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('weight_after_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('movement_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=True),
    sa.Column('reversed_by_movement_id', sa.Integer(), nullable=True),
    sa.Column('reversal_of_movement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['storage_locations.id'], ),
    sa.ForeignKeyConstraint(['reversal_of_movement_id'], ['stock_movements.id'], ),
    sa.ForeignKeyConstraint(['reversed_by_movement_id'], ['stock_movements.id'], ),
    sa.ForeignKeyConstraint(['stock_lot_id'], ['stock_lots.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['storage_locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movement_number')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index('ix_movement_lot_date', ['stock_lot_id', 'movement_date'], unique=False)
        batch_op.create_index('ix_movement_reference', ['reference_type', 'reference_id'], unique=False)
        batch_op.create_index('ix_movement_type_date', ['movement_type', 'movement_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_id'), ['id'], unique=False)

    op.create_table('tracking_stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.String(), nullable=True),
    sa.Column('to_stage', sa.String(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['production_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracking_stage_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracking_stage_history_id'), ['id'], unique=False)

    op.create_table('v3_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assembly_id', sa.Integer(), nullable=False),
    sa.Column('piece_mark', sa.String(length=100), nullable=False),
    sa.Column('profile_section', sa.String(length=200), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('length_mm', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('width_mm', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('thickness_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity_per_assembly', sa.Integer(), nullable=False),
    sa.Column('weight_each_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('inventory_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('weight_each_kg > 0', name='ck_component_weight_positive'),
    sa.ForeignKeyConstraint(['assembly_id'], ['v3_assemblies.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assembly_id', 'piece_mark', name='uq_component_assembly_piece')
    )
    with op.batch_alter_table('v3_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_v3_components_id'), ['id'], unique=False)

    op.create_table('material_consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_usage_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['material_usage_id'], ['material_usage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_consumption', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_consumption_id'), ['id'], unique=False)

    op.create_table('material_consumption_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_item_id', sa.Integer(), nullable=False),
    sa.Column('stock_lot_id', sa.Integer(), nullable=False),
    sa.Column('stock_movement_id', sa.Integer(), nullable=True),
    sa.Column('consumed_weight_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('consumed_qty', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('consumed_by', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['consumed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['production_item_id'], ['production_items_v2.id'], ),
    sa.ForeignKeyConstraint(['stock_lot_id'], ['stock_lots.id'], ),
    sa.ForeignKeyConstraint(['stock_movement_id'], ['stock_movements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_consumption_v2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_consumption_v2_id'), ['id'], unique=False)

    op.create_table('v3_component_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('instance_number', sa.Integer(), nullable=False),
    sa.Column('serial_tag', sa.String(length=100), nullable=True),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('stage_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'ON_HOLD', 'REWORK', name='componentstagestatus'), nullable=False),
    sa.Column('stage_updated_at', sa.DateTime(), nullable=True),
    sa.Column('stage_updated_by', sa.Integer(), nullable=True),
    sa.Column('stock_lot_id', sa.Integer(), nullable=True),
    sa.Column('heat_number', sa.String(length=100), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('is_scrapped', sa.Boolean(), nullable=True),
    sa.Column('scrap_reason', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('material_reserved', sa.Boolean(), nullable=True),
    sa.Column('material_issued', sa.Boolean(), nullable=True),
    sa.Column('material_consumed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['v3_components.id'], ),
    sa.ForeignKeyConstraint(['stage_updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stock_lot_id'], ['stock_lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id', 'instance_number', name='uq_instance_component_number'),
    sa.UniqueConstraint('serial_tag')
    )
    with op.batch_alter_table('v3_component_instances', schema=None) as batch_op:
        batch_op.create_index('ix_instance_component', ['component_id'], unique=False)
        batch_op.create_index('ix_instance_stage', ['current_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_v3_component_instances_id'), ['id'], unique=False)

    op.create_table('v3_revision_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.Enum('ADDED', 'REMOVED', 'MODIFIED', name='revisionchangetype'), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('field_changed', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('disposition', sa.Enum('REWORK', 'SCRAP_REMAKE', 'USE_AS_IS', 'CANCEL', name='dispositionaction'), nullable=True),
    sa.Column('disposition_by', sa.Integer(), nullable=True),
    sa.Column('disposition_at', sa.DateTime(), nullable=True),
    sa.Column('cost_impact', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['v3_components.id'], ),
    sa.ForeignKeyConstraint(['disposition_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['v3_drawing_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('v3_revision_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_v3_revision_changes_id'), ['id'], unique=False)

    op.create_table('v3_material_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_instance_id', sa.Integer(), nullable=False),
    sa.Column('stock_lot_id', sa.Integer(), nullable=True),
    sa.Column('inventory_id', sa.Integer(), nullable=True),
    sa.Column('reserved_weight_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('issued_weight_kg', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('consumed_weight_kg', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('returned_weight_kg', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('status', sa.Enum('RESERVED', 'ISSUED', 'CONSUMED', 'RETURNED', 'CANCELLED', name='reservationstatus'), nullable=False),
    sa.Column('reserved_by', sa.Integer(), nullable=True),
    sa.Column('reserved_at', sa.DateTime(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('issue_movement_id', sa.Integer(), nullable=True),
    sa.Column('consume_movement_id', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.CheckConstraint('reserved_weight_kg > 0', name='ck_reservation_weight_positive'),
    sa.ForeignKeyConstraint(['component_instance_id'], ['v3_component_instances.id'], ),
    sa.ForeignKeyConstraint(['consume_movement_id'], ['stock_movements.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['issue_movement_id'], ['stock_movements.id'], ),
    sa.ForeignKeyConstraint(['reserved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stock_lot_id'], ['stock_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('v3_material_reservations', schema=None) as batch_op:
        batch_op.create_index('ix_reservation_instance', ['component_instance_id'], unique=False)
        batch_op.create_index('ix_reservation_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_v3_material_reservations_id'), ['id'], unique=False)

    op.create_table('v3_stage_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_instance_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.String(length=50), nullable=True),
    sa.Column('to_stage', sa.String(length=50), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('transitioned_at', sa.DateTime(), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('station', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('deduction_result', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['component_instance_id'], ['v3_component_instances.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('v3_stage_transitions', schema=None) as batch_op:
        batch_op.create_index('ix_transition_instance', ['component_instance_id'], unique=False)
        batch_op.create_index('ix_transition_time', ['transitioned_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_v3_stage_transitions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('v3_stage_transitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_v3_stage_transitions_id'))
        batch_op.drop_index('ix_transition_time')
        batch_op.drop_index('ix_transition_instance')

    op.drop_table('v3_stage_transitions')
    with op.batch_alter_table('v3_material_reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_v3_material_reservations_id'))
        batch_op.drop_index('ix_reservation_status')
        batch_op.drop_index('ix_reservation_instance')

    op.drop_table('v3_material_reservations')
    with op.batch_alter_table('v3_revision_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_v3_revision_changes_id'))

    op.drop_table('v3_revision_changes')
    with op.batch_alter_table('v3_component_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_v3_component_instances_id'))
        batch_op.drop_index('ix_instance_stage')
        batch_op.drop_index('ix_instance_component')

    op.drop_table('v3_component_instances')
    with op.batch_alter_table('material_consumption_v2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_consumption_v2_id'))

    op.drop_table('material_consumption_v2')
    with op.batch_alter_table('material_consumption', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_consumption_id'))

    op.drop_table('material_consumption')
    with op.batch_alter_table('v3_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_v3_components_id'))

    op.drop_table('v3_components')
    with op.batch_alter_table('tracking_stage_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracking_stage_history_id'))

    op.drop_table('tracking_stage_history')
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_id'))
        batch_op.drop_index('ix_movement_type_date')
        batch_op.drop_index('ix_movement_reference')
        batch_op.drop_index('ix_movement_lot_date')

    op.drop_table('stock_movements')
    with op.batch_alter_table('stage_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_tracking_id'))

    op.drop_table('stage_tracking')
    with op.batch_alter_table('scrap_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrap_records_id'))

    op.drop_table('scrap_records')
    with op.batch_alter_table('reusable_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reusable_stock_id'))

    op.drop_table('reusable_stock')
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queries_id'))

    op.drop_table('queries')
    with op.batch_alter_table('material_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_usage_id'))

    op.drop_table('material_usage')
    with op.batch_alter_table('dispatch_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_line_items_id'))

    op.drop_table('dispatch_line_items')
    with op.batch_alter_table('v3_drawing_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_v3_drawing_revisions_id'))

    op.drop_table('v3_drawing_revisions')
    with op.batch_alter_table('v3_assemblies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_v3_assemblies_id'))

    op.drop_table('v3_assemblies')
    with op.batch_alter_table('stock_lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_lots_lot_number'))
        batch_op.drop_index(batch_op.f('ix_stock_lots_id'))
        batch_op.drop_index(batch_op.f('ix_stock_lots_heat_number'))
        batch_op.drop_index('ix_stock_lot_vendor_date')
        batch_op.drop_index('ix_stock_lot_material_qa')
        batch_op.drop_index('ix_stock_lot_location')
        batch_op.drop_index('ix_stock_lot_heat')

    op.drop_table('stock_lots')
    with op.batch_alter_table('stage_tracking_v2', schema=None) as batch_op:
        batch_op.drop_index('ix_stage_v2_item_status')
        batch_op.drop_index(batch_op.f('ix_stage_tracking_v2_id'))

    op.drop_table('stage_tracking_v2')
    with op.batch_alter_table('production_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_items_id'))

    op.drop_table('production_items')
    with op.batch_alter_table('grn_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grn_line_items_id'))

    op.drop_table('grn_line_items')
    with op.batch_alter_table('v3_stage_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_v3_stage_configs_id'))
        batch_op.drop_index('ix_stage_config_customer')

    op.drop_table('v3_stage_configs')
    with op.batch_alter_table('v3_drawings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_v3_drawings_id'))
        batch_op.drop_index(batch_op.f('ix_v3_drawings_drawing_number'))
        batch_op.drop_index('ix_drawing_status')
        batch_op.drop_index('ix_drawing_customer')

    op.drop_table('v3_drawings')
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_config_id'))

    op.drop_table('system_config')
    with op.batch_alter_table('production_items_v2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_items_v2_id'))

    op.drop_table('production_items_v2')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_settings_id'))

    op.drop_table('notification_settings')
    with op.batch_alter_table('material_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_mappings_id'))
        batch_op.drop_index(batch_op.f('ix_material_mappings_excel_name'))

    op.drop_table('material_mappings')
    with op.batch_alter_table('instructions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instructions_id'))

    op.drop_table('instructions')
    with op.batch_alter_table('goods_receipt_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_receipt_notes_id'))
        batch_op.drop_index(batch_op.f('ix_goods_receipt_notes_grn_number'))

    op.drop_table('goods_receipt_notes')
    with op.batch_alter_table('excel_uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_excel_uploads_id'))

    op.drop_table('excel_uploads')
    with op.batch_alter_table('dispatch_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_notes_id'))
        batch_op.drop_index(batch_op.f('ix_dispatch_notes_dispatch_number'))

    op.drop_table('dispatch_notes')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_user_date')
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index('ix_audit_entity')

    op.drop_table('audit_logs')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_id'))

    op.drop_table('activity_logs')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_id'))

    op.drop_table('vendors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('storage_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storage_locations_id'))

    op.drop_table('storage_locations')
    with op.batch_alter_table('role_notification_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_notification_settings_id'))

    op.drop_table('role_notification_settings')
    with op.batch_alter_table('number_sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_number_sequences_id'))

    op.drop_table('number_sequences')
    with op.batch_alter_table('material_master', schema=None) as batch_op:
        batch_op.drop_index('ix_material_type_grade')
        batch_op.drop_index(batch_op.f('ix_material_master_id'))
        batch_op.drop_index(batch_op.f('ix_material_master_code'))

    op.drop_table('material_master')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_id'))

    op.drop_table('inventory')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_id'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))

    op.drop_table('customers')
    # ### end Alembic commands ###
