"""add_valuation_columns_to_stock_movements

Revision ID: f9175aa2e862
Revises: 86fbcc9926b2
Create Date: 2026-05-18 10:50:25.494039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9175aa2e862'  # pragma: allowlist secret
down_revision: Union[str, None] = '86fbcc9926b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valuation_rate', sa.Numeric(precision=15, scale=4), nullable=True))
        batch_op.add_column(sa.Column('stock_value_change', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('balance_stock_value', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('balance_qty_kg', sa.Numeric(precision=15, scale=3), nullable=True))
        batch_op.add_column(sa.Column('posting_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fiscal_year', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_column('fiscal_year')
        batch_op.drop_column('posting_date')
        batch_op.drop_column('balance_qty_kg')
        batch_op.drop_column('balance_stock_value')
        batch_op.drop_column('stock_value_change')
        batch_op.drop_column('valuation_rate')

    # ### end Alembic commands ###
